language: rust

rust:
    - stable
    - beta
    - nightly

script:
    cd swt-rs
    cargo build -v;
    if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo test -v; fi;
    cargo doc -v;

after_success:
- curl http://docs.piston.rs/travis-doc-upload.sh | sh